language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.4
      env: TOXENV=py34-linux-package
    - python: 3.4
      env: TOXENV=docs

install:
  - pip install tox
  - pip install .

script:
  - tox -v

